<?php

namespace ContactBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastFivesMessages()
    {
        
    $entityManager = $this->getEntityManager();

    $query = $entityManager->createQuery(
        'SELECT c
        FROM ContactBundle\Entity\Contact c
        ORDER BY c.sendAt DESC'
    )->setMaxResults(5);

    return $query->execute();
    }
}
