app:
    resource: '@AppBundle/Controller/'
    type: annotation

image:
    resource: "@ImageBundle/Controller/"
    type:     annotation
    prefix:   /

ville_ville:
    resource: "@VilleBundle/Controller/VilleController.php"
    type:     annotation

partie_partie:
    resource: "@PartieBundle/Controller/PartieController.php"
    type:     annotation

ville:
    resource: "@VilleBundle/Controller/"
    type:     annotation
    prefix:   /

sport:
    resource: "@SportBundle/Controller/"
    type:     annotation
    prefix:   /

message:
    resource: "@MessageBundle/Controller/"
    type:     annotation
    prefix:   /

partie:
    resource: "@PartieBundle/Controller/"
    type:     annotation
    prefix:   /

role:
    resource: "@RoleBundle/Controller/"
    type:     annotation
    prefix:   /

utilisateur:
    resource: "@UtilisateurBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path: /login
    defaults:
        _controller: UtilisateurBundle:Utilisateur:login

login_check:
    path: /login_check

logout:
    path: /logout
