security:
    encoders:
        Symfony\Component\Security\Core\Utilisateur\Utilisateur: plaintext
        UtilisateurBundle\Entity\Utilisateur:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
    


    providers:
        main:
            entity:
                class:    UtilisateurBundle\Entity\Utilisateur
                property: username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern:   ^/login$
            anonymous: true 
        main:
            pattern:   ^/
            anonymous: true
            provider:  main 
            form_login:
                login_path:    login
                check_path:    login_check
                default_target_path: utilisateur_dashboard
            logout:
                path:          logout
                target:        homepage



    access_control:

    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
